'use strict';
const $ = s => document.querySelector(s);
const SDK = window.GenLayerSDK;
const RPC = 'https://studio.genlayer.com/api';
const EXPLORER = 'https://explorer-studio.genlayer.com';
let deployment, account, client, selected = null, record = null, busy = false;
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sleep = ms => new Promise(r => setTimeout(r, ms));
function notice(text, error = false) { $('#notice').textContent = text; $('#notice').className = error ? 'error' : ''; }
function ready() { if (!deployment?.address) throw Error('No verified deployment configured.'); if (!client) throw Error('Create a testnet session first.'); }
async function rpc(method, params) { const response = await fetch(RPC, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}); if (!response.ok) throw Error('RPC unavailable: HTTP '+response.status); const data = await response.json(); if (data.error) throw Error(data.error.message || JSON.stringify(data.error)); return data.result; }
async function read(method, args = []) { ready(); const data = await client.readContract({address:deployment.address,functionName:method,args}); return typeof data === 'string' ? JSON.parse(data) : data; }
function updateActions() { $('#seal').disabled = busy || !record || record.sealed || !account || record.owner.toLowerCase() !== account.address.toLowerCase(); $('#evaluate').disabled = busy || !record?.sealed || record.next_index >= record.proposals.length; $('#submit-details').hidden = !record || record.sealed; }
async function action(fn) { if(busy) return; busy = true; document.querySelectorAll('button').forEach(b=>b.disabled=true); try { await fn(); } catch(e) { notice(e.message || String(e), true); } finally {busy=false; document.querySelectorAll('button').forEach(b=>b.disabled=false); updateActions();} }
async function connect() { if (client) { notice('This tab already has a testnet signing session.'); return; } if (!SDK) throw Error('GenLayer SDK failed to load.'); let pk = sessionStorage.getItem('grantweave-burner'); if(!pk) {pk=SDK.generatePrivateKey();sessionStorage.setItem('grantweave-burner',pk);} account=SDK.createAccount(pk);client=SDK.createClient({chain:SDK.studionet,account});$('#wallet').textContent='Testnet burner: '+account.address+' · Session-only. Never send real assets.';$('#connect').textContent='Testnet session active';notice('Session active. Requesting testnet faucet…'); await client.request({method:'sim_fundAccount',params:[account.address,1e18]}); await loadRounds();notice('Testnet session ready. Credits are not GEN payments.'); }
async function loadRounds() { const ids=await read('list_rounds'); const container=$('#round-list');container.replaceChildren();for(const id of ids.slice().reverse()) {const button=document.createElement('button');button.className='round-item'+(id===selected?' selected':'');button.textContent=id;button.onclick=()=>action(()=>loadRound(id));container.append(button);} if(!ids.length) container.textContent='No on-chain rounds yet.'; }
function renderRound(data) { record=data;selected=data.id;$('#round-actions').hidden=false;const reserved=data.proposals.filter(p=>p.status==='RESERVED').reduce((sum,p)=>sum+p.amount,0);$('#round-view').innerHTML=`<div class="row"><div><p class="eyebrow">${esc(data.id)}</p><h2>${esc(data.title)}</h2></div><span class="badge">${data.sealed?'SEALED':'OPEN'}</span></div><p class="muted">${esc(data.rubric)}</p><p class="mono muted">Round owner: ${esc(data.owner)}</p><div class="stats"><div class="stat"><span>Budget</span><strong>${data.budget}</strong></div><div class="stat"><span>Reserved</span><strong>${reserved}</strong></div><div class="stat"><span>Remaining</span><strong>${data.remaining}</strong></div></div><p class="fine">Allocation credits only · ${data.next_index} / ${data.proposals.length} reviewed in submission order</p><div id="ledger">${data.proposals.length?data.proposals.map(p=>`<article class="proposal"><div class="row"><h3>${p.index+1}. ${esc(p.title)}</h3><span class="badge ${esc(p.status)}">${esc(p.status)}</span></div><p>${p.amount} credits requested · <span class="mono">${esc(p.applicant)}</span></p><a class="fine" href="${esc(p.url)}" target="_blank" rel="noopener">Pinned proposal source ↗</a><p class="mono muted">SHA-256: ${esc(p.digest)}</p>${p.result?.reason?`<p>${esc(p.result.reason)}</p><div class="fine">Eligibility: ${esc(p.result.eligibility)} · Duplication: ${esc(p.result.duplication)}</div>${(p.result.citations||[]).map(c=>`<blockquote><b>Source ${c.source}</b> — ${esc(c.quote)}</blockquote>`).join('')}<details><summary>Inspect recorded result</summary><pre>${esc(JSON.stringify(p.result,null,2))}</pre></details>`:'<p class="muted">Awaiting review after submissions are sealed.</p>'}</article>`).join(''):'<p class="muted">No proposals yet. Add the first pinned source below.</p>'}</div>`;updateActions();document.querySelectorAll('.round-item').forEach(b=>b.classList.toggle('selected',b.textContent===selected)); }
async function loadRound(id) { const data=await read('get_round',[id]);renderRound(data);notice('Fresh on-chain state loaded.'); }
function successful(tx) {const leader=tx.consensus_data?.leader_receipt?.[0];const execution=tx.tx_execution_result_name||leader?.execution_result;return tx.status==='FINALIZED'&&tx.result_name==='MAJORITY_AGREE'&&['SUCCESS','FINISHED_WITH_RETURN'].includes(execution);}
async function waitTransaction(hash) { for(let i=0;i<90;i++){try{const tx=await rpc('eth_getTransactionByHash',[hash]);if(tx&&['FINALIZED','UNDETERMINED','CANCELED'].includes(tx.status)){if(!successful(tx))throw Error('Transaction finished without confirmed successful execution. Inspect its explorer receipt; no success is assumed.');return tx;}}catch(e){if(e.message.includes('without confirmed'))throw e;if(i===89)throw e;}await sleep(10000);}throw Error('Transaction still pending. Do not resubmit blindly; inspect the saved hash and refresh on-chain state.'); }
async function write(method,args,rid) {ready();notice('Sending '+method+' to Studionet…');const hash=await client.writeContract({address:deployment.address,functionName:method,args,value:0n,leaderOnly:false});sessionStorage.setItem('grantweave-last-tx',hash);$('#tx').innerHTML=`Transaction: <a href="${EXPLORER}/tx/${esc(hash)}" target="_blank" rel="noopener">${esc(hash)} ↗</a>`;notice('Transaction submitted. Waiting for consensus AND successful execution…');await waitTransaction(hash);await loadRound(rid);await loadRounds();notice('Execution verified and on-chain state read back.');return hash;}
async function hashSource() {const form=$('#proposal-form');const url=form.elements.url.value; if(!/^https:\/\/raw\.githubusercontent\.com\/[A-Za-z0-9_-]+\/[A-Za-z0-9_.-]+\/[0-9a-f]{40}\/[A-Za-z0-9_./-]+\.(md|txt)$/.test(url)||url.split('/').slice(3).some(x=>['','.','..'].includes(x)))throw Error('Use a commit-pinned raw.githubusercontent.com .md or .txt URL.');const response=await fetch(url);if(!response.ok)throw Error('Source fetch failed: HTTP '+response.status);const bytes=await response.arrayBuffer();if(bytes.byteLength<20||bytes.byteLength>12000)throw Error('Source must contain 20–12,000 UTF-8 bytes.');new TextDecoder('utf-8',{fatal:true}).decode(bytes);const hash=await crypto.subtle.digest('SHA-256',bytes);form.elements.digest.value=Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');notice('SHA-256 computed from fetched source bytes. No transaction sent.');}
$('#connect').onclick=()=>action(connect);$('#refresh').onclick=()=>action(loadRounds);$('#reload').onclick=()=>action(()=>loadRound(selected));$('#seal').onclick=()=>action(()=>write('seal_round',[selected],selected));$('#evaluate').onclick=()=>action(()=>write('evaluate_next',[selected],selected));$('#hash').onclick=()=>action(hashSource);
$('#create-form').onsubmit=e=>{e.preventDefault();action(async()=>{const d=new FormData(e.target);const rid=d.get('id');await write('create_round',[rid,d.get('title'),d.get('rubric'),Number(d.get('budget'))],rid);});};
$('#proposal-form').onsubmit=e=>{e.preventDefault();action(async()=>{const d=new FormData(e.target);await write('submit_proposal',[selected,d.get('title'),d.get('url'),d.get('digest'),Number(d.get('amount'))],selected);});};
$('#example').onchange=e=>action(async()=>{const name=e.target.value;if(!name)return;const form=$('#proposal-form');form.elements.title.value=name.replaceAll('-',' ');form.elements.url.value='https://raw.githubusercontent.com/faisalnugroho/grantweave/184a498947dc32ce3be089f77d3e3542ec24cec9/examples/'+name+'.md';form.elements.amount.value=name==='accessibility'?30:name==='private-course'?20:name==='ambiguous'?10:40;$('#submit-details').open=true;await hashSource();});
(async()=>{try{const response=await fetch('./deployment.json',{cache:'no-store'});if(!response.ok)throw Error('Deployment configuration is unavailable.');deployment=await response.json();if(!/^0x[0-9a-fA-F]{40}$/.test(deployment.address||''))throw Error('No verified contract address configured yet.');$('#deployment').innerHTML=`Contract: <a href="${EXPLORER}/contracts/${esc(deployment.address)}" target="_blank" rel="noopener">${esc(deployment.address)} ↗</a>`;const last=sessionStorage.getItem('grantweave-last-tx');if(/^0x[0-9a-fA-F]{64}$/.test(last||''))$('#tx').innerHTML=`Last transaction in this tab: <a href="${EXPLORER}/tx/${last}" target="_blank" rel="noopener">${last} ↗</a>`;}catch(e){notice(e.message,true);$('#deployment').textContent='Deployment unavailable — writes disabled until configured.';}})();
window.GrantWeave={successful,renderRound};
